name: Hello Test
on:
  push:
    branches:
      - main
      - test

jobs:
  hello_job:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'dev' || github.ref_name }}
    steps:
      - name: Set up .env
        run: cp .env.${{ env.environment }} .env
      - name: Hello
        run: cat .env
