name: Hello Test
on:
  push:
    branches:
      - main
      - test

jobs:
  hello_job:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.ref_name == 'main' && 'dev' || github.ref_name }}
    environment: ${{ env.ENVIRONMENT }}
    steps:
      - name: Set up .env
        run: cp .env.${{ env.ENVIRONMENT }} .env
      - name: Show .env
        run: cat .env
      - name: Hello
        run: echo ${{ vars.HELLO }}
