name: Hello Test
on:
  push:
    branches:
      - main
      - test

jobs:
  hello_job:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: hello
        run: echo ${{ vars.HELLO }}
